### ISSUE TITLE
video screen inside 360 image space 

### ISSUE THREAD

**Issue by donblaauw** [pchen66/panolens.js#119]
an acquaintance of mine uses aframe in his VR platform. Would this be possible within Panolens too? Same lib maybe?

https://virtualscreen.vrmaster.co/

**Comment by donblaauw** [comment]
it uses Aframe AVideoPlayer.js Is this usable within "our' platform?" I cant get video to run on mu iphone 6 inside a 360 still world

**Comment by pchen66** [comment]
Panolens doesn't require additional dependency on video playing, it's built-in functionality by default. Take a look at this example on desktop / mobile: [Panorama UI](http://pchen66.github.io/Panolens/examples/panorama_ui.html)

**Comment by donblaauw** [comment]
looks great.. but could this method also work without actual clicking on a button.. IN VR mode “gazing”  should also be possible, mean.
got a codePen example? 😄

Met vriendelijke groet,

Don Blaauw

----------------------------------------------------

Don Blaauw
Creative Director of playful Interactives
studio No More Mondays 

Werkwarenhuis
Tramkade 20G,
5211 VB  's-Hertogenbosch

Tel:        +31 (6) 24581166 
Mail:      don@nomomo.nl <mailto:don@nomomo.nl> 
Website: www.nomomo.nl <http://www.nomomo.nl/> 
Twitter:   twitter.com/donnomomo <https://twitter.com/donnomomo>
LinkedIn: www.linkedin.com/in/donblaauw <http://www.linkedin.com/in/donblaauw> 



No More Mondays
'bringing the FUN back into function"

Kids Love Cards
‘Transmedial storytelling, using fun to educate. ”
Website: www.kidslovecards.nl <http://www.kidslovecards.nl/> 

VRhalen.nl
‘The story is all around you!”
Website: www.vrhalen.nl <http://www.vrhalen.nl/> 

----------------------------------------------------










On Feb 22, 2018, at 07:10, Ray Chen <notifications@github.com> wrote:

Panolens doesn't require additional dependency on video playing, it's built-in functionality by default. Take a look at this example on desktop / mobile: Panorama UI <http://pchen66.github.io/Panolens/examples/panorama_ui.html>

**Comment by donblaauw** [comment]
also the vid controls don’t work on sensor VR mode, so without clicking?
the controls  aren’t duplicated?

Don

**Comment by pchen66** [comment]
It's working as expected. The reason why the you cannot see it playing is because most mobile browser doesn't allow play without a user gesture. Under the hood it's giving this error from browser `DOMException: play() can only be initiated by a user gesture.` The example you gave earlier force you to "click" on the "Allow VR video" button before you start the experience, which indirectly triggers video to play and pause. This is not an elegant solution. However, Panolens will not be limited or force user to do this, but you can do that on the application level.

The actual click event listener from the demo you gave
```
video_permission.style.display = 'none';
that.elVideo.play();
that.elVideo.pause();
```

On a side note, if you're using Android, Chrome for Android allows video autoplay without user gesture.
<img width="380" alt="screen shot 2018-02-22 at 10 40 04 am" src="https://user-images.githubusercontent.com/2421225/36557335-d47b8e2c-17bc-11e8-952d-5eb57476c70f.png">

**Comment by donblaauw** [comment]
That first not elegant click could work yeah. But tell me, are panolens video controls also working in stereo mode (VR) e.g. controlling play and or pause ?
