### ISSUE TITLE
How to display reticle before hover element?

### ISSUE THREAD

**Issue by yglin** [pchen66/panolens.js#122]
First I want to thank you for this amazing library, it really helps our project development.

We have the issue of reticle sprite rendered behind infospot's hover element, notice that red spot(the reticle) as camera focus disappear in the second screenshot.

![messageimage_1518575724599](https://user-images.githubusercontent.com/5110555/36191411-f7c6a982-1197-11e8-9587-33c9482ed675.jpg)

![messageimage_1518575741470](https://user-images.githubusercontent.com/5110555/36191095-984f5720-1196-11e8-94fc-d30d6c2f7093.jpg)

So is there any way to render the reticle sprite before hover element? We need this so that we can also interact hover element through reticle object.

**Comment by pchen66** [comment]
The reason why the red dot disappears is because of rendering order. The 3D layer is at the bottom (reticle) and a div container (hover element) on the top. This was originally design for display purpose, so currently there an easy way to what you were asking. 

However, if you want it to be interactive, you can implement hover element directly in 3D, which gives you total control of what you want to achieve. As for video rendering, you can take a look at this example [Panorama UI](http://pchen66.github.io/Panolens/examples/panorama_ui.html)

**Comment by rsjackson101** [comment]
Hi

I am experiencing the same issue with the reticle being on the layer behind, but don't fully understand the way to change the order to have the hover element in 3D as briefly described above.  I would appreciate if you could please explain it a bit further or if you have a code example that I could look at?  Thanks

**Comment by markusand** [comment]
> However, if you want it to be interactive, you can implement hover element directly in 3D, which gives you total control of what you want to achieve. As for video rendering, you can take a look at this example [Panorama UI](http://pchen66.github.io/Panolens/examples/panorama_ui.html)

Link is broken. Could you please dive deeper into this?

**Comment by paella55** [comment]
> Link is broken. Could you please dive deeper into this?

I think he created a better example with this [PanoTheater](PanoTheater) and that's why he deprecated the previous one. The code can be found [here](https://github.com/pchen66/pchen66.github.io/tree/master/PanoTheater)
