### ISSUE TITLE
How to add text spot

### ISSUE THREAD

**Issue by aramvr** [pchen66/panolens.js#137]
Hi. I'm trying to add an html button instead of png button. how is that possible?

**Comment by webfalcon** [comment]
I really need html marker feature. please help me to have it or please prompt me how to build with panolens or threejs

**Comment by webfalcon** [comment]
I need to add this button as marker. https://codepen.io/anon/pen/QryxWx
Also tried to add gif button for animation but animation not working in this case. Also svg animation don't works.

**Comment by claytonrothschild** [comment]
Did you ever figure this out? I tried following a guide here: http://learningthreejs.com/blog/2013/04/30/closing-the-gap-between-html-and-webgl/ and just adding the texture to PANOLENS.Panorama (since Panorama is an implementation of THREE.Scene). I had to add the CSS3D renderer from Three.JS (https://github.com/mrdoob/three.js/blob/master/examples/js/renderers/CSS3DRenderer.js). 

I got really close but ran out of time. This seems to be the approach to go though.
