### ISSUE TITLE
Infospot debugging not working

### ISSUE THREAD

**Issue by bendemaree** [pchen66/panolens.js#16]
It looks like using `Ctrl` and clicking/hovering to place Infospots is no longer outputting correct coordinates. Using the Infospot example, you can see that it's correct when you are over the Infospot itself:

```
panolens.min.js:3 { -4668.16, -1612.16, -724.72 }
panolens.min.js:3 { -4671.96, -1604.87, -717.87 }
panolens.min.js:3 { -4674.45, -1604.54, -702.96 }
panolens.min.js:3 { -4678.18, -1604.03, -680.59 }
panolens.min.js:3 { -4683.22, -1596.58, -666.30 }
panolens.min.js:3 { -4688.25, -1589.14, -652.02 }
panolens.min.js:3 { -4691.98, -1588.64, -629.69 }
panolens.min.js:3 { -4695.70, -1588.14, -607.38 }
panolens.min.js:3 { -4699.42, -1587.64, -585.07 }
panolens.min.js:3 { 94.37, -32.29, -4.19 }
panolens.min.js:3 { -4729.79, -1580.54, 236.81 }
panolens.min.js:3 { -4729.50, -1579.32, 250.91 }
panolens.min.js:3 { -4731.77, -1571.26, 264.37 }
panolens.min.js:3 { -4731.63, -1570.65, 271.40 }
panolens.min.js:3 { -4734.04, -1563.21, 277.81 }
panolens.min.js:3 { -4736.30, -1555.18, 291.23 }
panolens.min.js:3 { -4738.70, -1547.75, 297.62 }
panolens.min.js:3 { -4740.73, -1540.21, 303.98 }
panolens.min.js:3 { -4744.35, -1525.01, 316.66 }
```

That different set in the middle seems to be the intended coordinates.

**Comment by pchen66** [comment]
Thanks for reporting this. The result is expected since the output coord is against the panorama sphere. The different set (infospot itself) is due to [approximation issue](http://stackoverflow.com/questions/36123458/three-raycaster-not-working-properly-with-scaled-three-sprite) in three.js r75. The reason we cannot see the newly created infospot is because it's too far away. With larger scaling value `new PANOLENS.Infospot( 300, PANOLENS.DataImage.Info )` you should be able to see it. I'll consolidate the scaling factor so that it's consistent.

**Comment by pchen66** [comment]
I've updated the [infospot example](http://pchen66.github.io/Panolens/examples/panorama_infospot.html) with proper scaling. When hovering on top of an infospot, it should output exactly where it attaches to.
<img width="228" alt="screen shot 2016-05-19 at 10 20 36" src="https://cloud.githubusercontent.com/assets/2421225/15417938/fe1fedde-1e0f-11e6-9c3f-ca62d2cac5cb.png">

**Comment by dmw4176** [comment]
pchen66 how do I view the infospot coordinates via the console? I tried holding down the ctrl key and the coordinates are not showing. I am trying to find an easier way to add the infospots without trying to manually figure out where they would go in my pano viewer. Any help is highly appreciated.

DW
