### ISSUE TITLE
Sensor is not working on web browsers

### ISSUE THREAD

**Issue by dev-ahmad** [pchen66/panolens.js#203]
Hello everyone, I've created this pen https://codepen.io/ahmadrhaddad/pen/QWWNBBK, If you opened it from codepen on mobile, the sensor will work fine, but if you export the project and you opened it from mobile also 'from local server' it will work EXCEPT sensor mode, anyone have an idea, or can help me please?

**Comment by dev-ahmad** [comment]
@zcherries @pchen66 Help please ...

**Comment by johannesberdin** [comment]
I assume you‘re experiencing this issue on an iOS mobile device. There is a change in how to handle orientation/motion since iOS 12, resp. iOS 13 regarding how to access those data - the net is full of articles and complaints about that.

There seems to be a fix for iOS 12 users by just setting a switch in the device‘s settings. For iOS 13, the website needs to request permission for motion/orientation. This article could be helpful for fixing this issue: https://medium.com/flawless-app-stories/how-to-request-device-motion-and-orientation-permission-in-ios-13-74fc9d6cd140

**Comment by claytonrothschild** [comment]
@johannesberdin is spot on. The brand new `DeviceMotionEvent.requestPermission()` is really helpful after Apple turned off device orientation access by default in iOS 12. Add it to your solution.

Anyway, @dev-ahmad your problem is likely CORS related. It sounds like you already have device orientation permissions set up because it worked fine for you on codepen but not local server.

I bet you are not running https on local server.

The issue is that Safari will restrict some events, especially motion events, from running on unsecure websites over HTTP. You must set up and enable HTTPS and the events will then be triggered. Try that.
