### ISSUE TITLE
How to disable rotation of infospot on panorama rotation

### ISSUE THREAD

**Issue by IamITGeneralist** [pchen66/panolens.js#215]
I have added infospots on cube panorama. When I am rotating panorama then all of the infospots also moving in reverse direction of panorama rotation. 

How to fix infospots when I am rotating panoramas?

@pchen66 Please help me about this.

**Comment by cgncalle** [comment]
Hey, i have the same problem. Did you solve this issue? THX

**Comment by GiorgosK** [comment]
It seems what we want is implemented here https://pchen66.github.io/Panolens/examples/panorama_reticle.html
the zodiac names appear to be part of the scene and follow the angle of rotation thus changing shape depending on the rotation of the view (seems to be what is described above)

I have not figured out how it is done yet

seems this issue is also regarding the same thing https://github.com/pchen66/panolens.js/issues/161
