### ISSUE TITLE
Some infospots sometimes fail to display in Safari

### ISSUE THREAD

**Issue by bendemaree** [pchen66/panolens.js#22]
Hello @pchen66. Thanks for addressing #16 earlier!

After noticing it in my own project, I'm seeing one or the other of the infospots on the example infospot panorama fail to display in Safari (I'm on 9.1.1). It seems to be random which loads, or if both load; I suspect there is a race condition involved because it appears having some items cached mitigates the issue (thus, it's easiest to replicate in private browsing or with the cache off).

Any hope? My stab in the dark would be that perhaps Safari doesn't handle the image load event the same way as others (Chrome works well) and it's racing to display before the infospot image is available.

**Comment by pchen66** [comment]
Thanks for reporting! I've seen textures not being rendered properly on mobile devices but not on the desktop. It was due to image texture returns size 0,0 sometimes. #23 should fix the issue. Can you try to load [Infospot_focus](http://pchen66.github.io/Panolens/examples/panorama_infospot_focus.html) to see if it's still reproducible? I tried several time on Safari 9.1.1 but didn't notice any display issue.

**Comment by bendemaree** [comment]
Hi @pchen66, the `infospot_focus` example seems to work well for me; I've pulled it in and things look improved in my project as well. 😄

I had the same issue on mobile in both Chrome and Safari, but it's iOS, so they're both WebKit anyway. I wonder if that ties all of this together.

Thank you!

**Comment by pchen66** [comment]
I'm curious if you're still having the issue? [infospot_foucs](http://pchen66.github.io/Panolens/examples/panorama_infospot_focus.html). Seems related to #25

**Comment by bendemaree** [comment]
@pchen66 I had already switched to PNG-based infospot icons for this reason. 😉 Since the fix in #23 I haven't seen the issue.
