### ISSUE TITLE
Prev/Next Buttons?

### ISSUE THREAD

**Issue by atlance01** [pchen66/panolens.js#74]
Hi there,

I'm using code based off your "Simple Gallery" code that you've provided. I've got everything running smoothly. 

However, I'd like to be able to add a next and previous button that would navigate through the image in the gallery. I've tried using previousElementSibling and nextElementSibling but this won't get all of the image in my gallery. Could you help with this?

**Comment by pchen66** [comment]
Hi, 
The "Simple Gallery" example was to demonstrate dynamic creation / disposal of panorama every single time you click. In order to to navigate through all the list, you can simply store the reference and index to each panorama and cycle them through when you click "Next / Prev" buttons. The final step would be set the corresponding panorama by `PANOLENS.Viewer`. For example, 
```
// Set current panorama to be the index 2 in the panorama reference list 
viewer.setPanorama( PANORAMA_LIST[2] );
```

**Comment by atlance01** [comment]
Thanks, that gives me a good direction to go in.
