### ISSUE TITLE
Linking panoramas

### ISSUE THREAD

**Issue by aaavvv07** [pchen66/panolens.js#76]
I'm trying to link a few panoramas. The link supposed to be in certain position on the screen.  I was trying to use panorama_linking as an example but in firefox I get completely different mouse coordinates from the coordinates in example's html. In example's html the coordinates of infospot is ( -74.56, -58.83, 31.10 ), but firefox for the same infospot gives me these coordinates - { 3690.64, -2912.02, 1539.42 }. What I'm doing wrong? How to get right coordinates?

Thanks, 
Alex

**Comment by pchen66** [comment]
Hello,

You're doing correctly. Actually the coordinates in the example is uniformly the same with your coordinates. It was due to the radius of the panorama sphere. There was a time the default radius is 100. It turns out too limited in the ordering, so it was scaled up to 50 times larger to be 5000. I should update the example so it matches. 
```
[ -74.56, -58.83, 31.10 ] * 49.4989 = [ -3690.64, -2912.02, 1539.41 ]
```

**Comment by aaavvv07** [comment]
Hello, 

Thank you for your answer. But still I can't figure this out. I'm using your equation and trying to put infospot into position like (60.0, 0.0, 80.0). Then I'm checking the mouse coordinates in firefox and this infospot has coordinates like { 2967.98, 0.00, -3957.31 }, but more interesting, that the closest mouse position to the infospot (but not over infospot)  has coordinates like { -3127.38, -153.03, -3853.34 }. it does make no sense to me. Could you please explain a bit the logic of it?

**Comment by pchen66** [comment]
The linking logic is based on raycasting from the center of a panorama to another. Since it's bi-directional so it creates an auto-generated infospot on each panorama based on relative location. 

There's one thing might not be obvious (I changed on dev branch) is that the console output is world coordinate not local coordinate. Please try this codepen example[ Console Output Debug](https://codepen.io/pchen66/pen/owLYYG) as well as [debug mode](https://s.codepen.io/pchen66/debug/owLYYG/) (where you can see console information) and let me know if this works for you. Make sure to refresh the page because it's not instantly update when you try to save it. 

Or use dev version, which outputs coordinates relative to panorama instead of world (https://rawgit.com/pchen66/panolens.js/dev/build/panolens.min.js) in your script to see if that's what you're looking for.

**Comment by aaavvv07** [comment]
Hello,

thank you for your explanation. I'll try to do as you said. It's obvious for me now, that I need to get more knowledge about how your script and three.js are working.

Thanks and regards,
Alex
