### ISSUE TITLE
Zoom In/Out functionality not working on android devices

### ISSUE THREAD

**Issue by mashakir** [pchen66/panolens.js#87]
Zoom In/Out functionality not working on android devices at all. Working fine on ios

**Comment by pchen66** [comment]
Confirmed there's bug in old `THREE.OrbitControls` where pinch is relying on `scale` property in TouchEvent but it's undefined on Android. Fixed in `dev` branch with commit 92a5bdd41b451940358fb8630e44aaef6a090609. Give a try with [Panorama Image](https://pchen66.github.io/Panolens/examples/panorama_image.html) example on Android.
