### ISSUE TITLE
Panoramas should be at different position error

### ISSUE THREAD

**Issue by randypng** [pchen66/panolens.js#89]
Adding two ImagePanoramas throws a "Panoramas should be at different position" warning. Any ideas?

```
var scene1 = new PANOLENS.ImagePanorama( 'assets/img/demoV3/living.jpg' );
var scene2 = new PANOLENS.ImagePanorama( 'assets/img/demoV3/dining.jpg' );

var viewer = new PANOLENS.Viewer();
viewer.add(scene1);
viewer.add(scene2);

scene1.link(scene2, new THREE.Vector3(4945.06, -367.34, -604.45));
scene2.link(scene1, new THREE.Vector3(-2942.35, 1499.04, -3744.54));
```

**Comment by pchen66** [comment]
Since r9 there's no restriction on overlapping panoramas. Here's the commit that removes the warning from r8 to r9 https://github.com/pchen66/panolens.js/commit/7fb653df7100bf3307f11b45fc70d65d243ca9bf#diff-2583b35de2c06249826b44841d036143L361 The idea behind this to implement basic cross-fade support. If you update to r9 above should be no more warning: https://github.com/pchen66/panolens.js/blob/master/build/panolens.min.js
