### ISSUE TITLE
IE11 "Object doesn't support property or method isNaN" for videopanos

### ISSUE THREAD

**Issue by Geddo** [pchen66/panolens.js#95]
Testet on win10 with the latest dev-branch on my local xampp. Also appears on your example pag (http://pchen66.github.io/Panolens/examples/panorama_video.html).

**Comment by pchen66** [comment]
The error message is due to `Number.isNaN` is [not support on IE11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) . Even with polyfil to get rid of this message, Three.JS isn't happy with IE11's `texImage2D` implementation. So in this case we won't fix for IE11 on VideoPanorama issue.
